name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      GOFLAGS: -mod=vendor
      GOPROXY: "https://proxy.golang.org,direct"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-southwest1-docker.pkg.dev

      - name: 'Build image'
        run: docker build -t europe-southwest1-docker.pkg.dev/notely-462309/notely-ar-repo/notely:latest .

      - name: 'Push image'
        run: docker push europe-southwest1-docker.pkg.dev/notely-462309/notely-ar-repo/notely:latest
